// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthorizationCode = `-- name: CreateAuthorizationCode :one
INSERT INTO authorization_codes
(code, user_id, client_id, redirect_uri, scope, code_challenge, expires_at, created_at)
VALUES
($1, $2, $3, $4, $5, $6, $7, NOW())
RETURNING code, user_id, client_id, redirect_uri, scope, code_challenge, code_challenge_method, expires_at, used, created_at
`

type CreateAuthorizationCodeParams struct {
	Code          string             `db:"code" json:"code"`
	UserID        uuid.UUID          `db:"user_id" json:"userId"`
	ClientID      string             `db:"client_id" json:"clientId"`
	RedirectUri   string             `db:"redirect_uri" json:"redirectUri"`
	Scope         *string            `db:"scope" json:"scope"`
	CodeChallenge *string            `db:"code_challenge" json:"codeChallenge"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
}

func (q *Queries) CreateAuthorizationCode(ctx context.Context, db DBTX, arg CreateAuthorizationCodeParams) (AuthorizationCode, error) {
	row := db.QueryRow(ctx, createAuthorizationCode,
		arg.Code,
		arg.UserID,
		arg.ClientID,
		arg.RedirectUri,
		arg.Scope,
		arg.CodeChallenge,
		arg.ExpiresAt,
	)
	var i AuthorizationCode
	err := row.Scan(
		&i.Code,
		&i.UserID,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scope,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredAuthorizationCodes = `-- name: DeleteExpiredAuthorizationCodes :many
DELETE FROM authorization_codes 
WHERE expires_at < NOW()
RETURNING code, user_id, client_id, redirect_uri, scope, code_challenge, code_challenge_method, expires_at, used, created_at
`

func (q *Queries) DeleteExpiredAuthorizationCodes(ctx context.Context, db DBTX) ([]AuthorizationCode, error) {
	rows, err := db.Query(ctx, deleteExpiredAuthorizationCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorizationCode
	for rows.Next() {
		var i AuthorizationCode
		if err := rows.Scan(
			&i.Code,
			&i.UserID,
			&i.ClientID,
			&i.RedirectUri,
			&i.Scope,
			&i.CodeChallenge,
			&i.CodeChallengeMethod,
			&i.ExpiresAt,
			&i.Used,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const useAuthorizationCode = `-- name: UseAuthorizationCode :exec
UPDATE authorization_codes
SET used = 1
WHERE code = $1
`

func (q *Queries) UseAuthorizationCode(ctx context.Context, db DBTX, code string) error {
	_, err := db.Exec(ctx, useAuthorizationCode, code)
	return err
}
