// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jwks.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateKey = `-- name: ActivateKey :many
UPDATE jwk_keys
SET is_active = (kid = $1)
RETURNING kid, private_key_pem, public_key_pem, algorithm, is_active, created_at, expires_at
`

func (q *Queries) ActivateKey(ctx context.Context, db DBTX, kid string) ([]JwkKey, error) {
	rows, err := db.Query(ctx, activateKey, kid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JwkKey
	for rows.Next() {
		var i JwkKey
		if err := rows.Scan(
			&i.Kid,
			&i.PrivateKeyPem,
			&i.PublicKeyPem,
			&i.Algorithm,
			&i.IsActive,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNewRs256Key = `-- name: CreateNewRs256Key :one
INSERT INTO jwk_keys (kid, private_key_pem, public_key_pem, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING kid, private_key_pem, public_key_pem, algorithm, is_active, created_at, expires_at
`

type CreateNewRs256KeyParams struct {
	Kid           string             `db:"kid" json:"kid"`
	PrivateKeyPem string             `db:"private_key_pem" json:"privateKeyPem"`
	PublicKeyPem  string             `db:"public_key_pem" json:"publicKeyPem"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
}

func (q *Queries) CreateNewRs256Key(ctx context.Context, db DBTX, arg CreateNewRs256KeyParams) (JwkKey, error) {
	row := db.QueryRow(ctx, createNewRs256Key,
		arg.Kid,
		arg.PrivateKeyPem,
		arg.PublicKeyPem,
		arg.ExpiresAt,
	)
	var i JwkKey
	err := row.Scan(
		&i.Kid,
		&i.PrivateKeyPem,
		&i.PublicKeyPem,
		&i.Algorithm,
		&i.IsActive,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredKey = `-- name: DeleteExpiredKey :many
DELETE FROM jwk_keys WHERE expires_at < NOW()
RETURNING kid, private_key_pem, public_key_pem, algorithm, is_active, created_at, expires_at
`

func (q *Queries) DeleteExpiredKey(ctx context.Context, db DBTX) ([]JwkKey, error) {
	rows, err := db.Query(ctx, deleteExpiredKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JwkKey
	for rows.Next() {
		var i JwkKey
		if err := rows.Scan(
			&i.Kid,
			&i.PrivateKeyPem,
			&i.PublicKeyPem,
			&i.Algorithm,
			&i.IsActive,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJwksKey = `-- name: GetJwksKey :one
SELECT kid, private_key_pem, public_key_pem, algorithm, is_active, created_at, expires_at FROM jwk_keys
WHERE kid = $1
AND expres_at > NOW()
`

func (q *Queries) GetJwksKey(ctx context.Context, db DBTX, kid string) (JwkKey, error) {
	row := db.QueryRow(ctx, getJwksKey, kid)
	var i JwkKey
	err := row.Scan(
		&i.Kid,
		&i.PrivateKeyPem,
		&i.PublicKeyPem,
		&i.Algorithm,
		&i.IsActive,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listKeys = `-- name: ListKeys :many
SELECT kid, private_key_pem, public_key_pem, algorithm, is_active, created_at, expires_at FROM jwk_keys WHERE expires_at > NOW()
`

func (q *Queries) ListKeys(ctx context.Context, db DBTX) ([]JwkKey, error) {
	rows, err := db.Query(ctx, listKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JwkKey
	for rows.Next() {
		var i JwkKey
		if err := rows.Scan(
			&i.Kid,
			&i.PrivateKeyPem,
			&i.PublicKeyPem,
			&i.Algorithm,
			&i.IsActive,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
