// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthorizationCode struct {
	Code                string             `db:"code" json:"code"`
	UserID              uuid.UUID          `db:"user_id" json:"userId"`
	ClientID            string             `db:"client_id" json:"clientId"`
	RedirectUri         string             `db:"redirect_uri" json:"redirectUri"`
	Scope               *string            `db:"scope" json:"scope"`
	CodeChallenge       *string            `db:"code_challenge" json:"codeChallenge"`
	CodeChallengeMethod *string            `db:"code_challenge_method" json:"codeChallengeMethod"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
	Used                *bool              `db:"used" json:"used"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type JwkKey struct {
	Kid           string             `db:"kid" json:"kid"`
	PrivateKeyPem string             `db:"private_key_pem" json:"privateKeyPem"`
	PublicKeyPem  string             `db:"public_key_pem" json:"publicKeyPem"`
	Algorithm     string             `db:"algorithm" json:"algorithm"`
	IsActive      bool               `db:"is_active" json:"isActive"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
}

type User struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Username      string             `db:"username" json:"username"`
	Email         string             `db:"email" json:"email"`
	PasswordHash  string             `db:"password_hash" json:"passwordHash"`
	EmailVerified bool               `db:"email_verified" json:"emailVerified"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}
