// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jwks.sql

package queries

import (
	"context"
)

const getJwksKey = `-- name: GetJwksKey :one
SELECT kid, private_key_pem, public_key_pem, algorithm, is_active, created_at, expires_at FROM jwk_keys
WHERE kid = $1
AND expres_at > NOW()
`

func (q *Queries) GetJwksKey(ctx context.Context, db DBTX, kid string) (JwkKey, error) {
	row := db.QueryRow(ctx, getJwksKey, kid)
	var i JwkKey
	err := row.Scan(
		&i.Kid,
		&i.PrivateKeyPem,
		&i.PublicKeyPem,
		&i.Algorithm,
		&i.IsActive,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listKeys = `-- name: ListKeys :many
SELECT kid, private_key_pem, public_key_pem, algorithm, is_active, created_at, expires_at FROM jwk_keys WHERE expires_at > NOW()
`

func (q *Queries) ListKeys(ctx context.Context, db DBTX) ([]JwkKey, error) {
	rows, err := db.Query(ctx, listKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JwkKey
	for rows.Next() {
		var i JwkKey
		if err := rows.Scan(
			&i.Kid,
			&i.PrivateKeyPem,
			&i.PublicKeyPem,
			&i.Algorithm,
			&i.IsActive,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
